/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ams.newcalib;

/**
 *
 * @author control
 */
public class DlgNewCalib extends javax.swing.JDialog {

    /**
     * Creates new form DlgNewCalib
     */
    public DlgNewCalib(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox2 = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jTextField56 = new javax.swing.JTextField();
        jTextField57 = new javax.swing.JTextField();
        jTextField58 = new javax.swing.JTextField();
        jTextField59 = new javax.swing.JTextField();
        jTextField60 = new javax.swing.JTextField();
        jTextField61 = new javax.swing.JTextField();
        jTextField62 = new javax.swing.JTextField();
        jTextField63 = new javax.swing.JTextField();
        jTextField64 = new javax.swing.JTextField();
        jTextField65 = new javax.swing.JTextField();
        jTextField66 = new javax.swing.JTextField();
        jTextField67 = new javax.swing.JTextField();
        jTextField68 = new javax.swing.JTextField();
        jTextField69 = new javax.swing.JTextField();
        jTextField70 = new javax.swing.JTextField();
        jTextField71 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jCheckBox2.setText("Использовать новую калибровку  для вычисления напряжения на аноде");
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(10, 70, 580, 22);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(10, 120, 80, 30);

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("I, мкА");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 100, 80, 11);

        jLabel2.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Uизм.(А-К), В");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 100, 80, 11);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(100, 120, 80, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(190, 120, 80, 30);

        jLabel3.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Uизм.(сопр.), В");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 100, 80, 11);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(280, 120, 80, 30);

        jLabel4.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Uadc, В");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 100, 80, 11);

        jTextField6.setEnabled(false);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(370, 120, 80, 30);

        jLabel5.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("R, кОм");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 100, 80, 11);

        jTextField7.setEnabled(false);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(460, 120, 80, 30);

        jLabel6.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("A");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(460, 100, 80, 11);

        jTextField8.setEnabled(false);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(550, 120, 80, 30);

        jLabel7.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("B");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(550, 100, 80, 11);

        jTextField9.setEnabled(false);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(550, 150, 80, 30);

        jTextField10.setEnabled(false);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(460, 150, 80, 30);

        jTextField11.setEnabled(false);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(370, 150, 80, 30);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(280, 150, 80, 30);
        getContentPane().add(jTextField13);
        jTextField13.setBounds(190, 150, 80, 30);
        getContentPane().add(jTextField14);
        jTextField14.setBounds(100, 150, 80, 30);
        getContentPane().add(jTextField15);
        jTextField15.setBounds(10, 150, 80, 30);

        jTextField16.setEnabled(false);
        getContentPane().add(jTextField16);
        jTextField16.setBounds(550, 180, 80, 30);

        jTextField17.setEnabled(false);
        getContentPane().add(jTextField17);
        jTextField17.setBounds(460, 180, 80, 30);

        jTextField18.setEnabled(false);
        getContentPane().add(jTextField18);
        jTextField18.setBounds(370, 180, 80, 30);
        getContentPane().add(jTextField19);
        jTextField19.setBounds(280, 180, 80, 30);
        getContentPane().add(jTextField20);
        jTextField20.setBounds(190, 180, 80, 30);
        getContentPane().add(jTextField21);
        jTextField21.setBounds(100, 180, 80, 30);
        getContentPane().add(jTextField22);
        jTextField22.setBounds(10, 180, 80, 30);
        getContentPane().add(jTextField23);
        jTextField23.setBounds(10, 210, 80, 30);
        getContentPane().add(jTextField24);
        jTextField24.setBounds(100, 210, 80, 30);
        getContentPane().add(jTextField25);
        jTextField25.setBounds(190, 210, 80, 30);
        getContentPane().add(jTextField26);
        jTextField26.setBounds(280, 210, 80, 30);

        jTextField27.setEnabled(false);
        getContentPane().add(jTextField27);
        jTextField27.setBounds(370, 210, 80, 30);

        jTextField28.setEnabled(false);
        getContentPane().add(jTextField28);
        jTextField28.setBounds(460, 210, 80, 30);

        jTextField29.setEnabled(false);
        getContentPane().add(jTextField29);
        jTextField29.setBounds(550, 210, 80, 30);

        jTextField30.setEnabled(false);
        getContentPane().add(jTextField30);
        jTextField30.setBounds(550, 240, 80, 30);

        jTextField31.setEnabled(false);
        getContentPane().add(jTextField31);
        jTextField31.setBounds(460, 240, 80, 30);

        jTextField32.setEnabled(false);
        getContentPane().add(jTextField32);
        jTextField32.setBounds(370, 240, 80, 30);
        getContentPane().add(jTextField33);
        jTextField33.setBounds(280, 240, 80, 30);
        getContentPane().add(jTextField34);
        jTextField34.setBounds(190, 240, 80, 30);
        getContentPane().add(jTextField35);
        jTextField35.setBounds(100, 240, 80, 30);
        getContentPane().add(jTextField36);
        jTextField36.setBounds(10, 240, 80, 30);

        jTextField37.setEnabled(false);
        getContentPane().add(jTextField37);
        jTextField37.setBounds(550, 270, 80, 30);

        jTextField38.setEnabled(false);
        getContentPane().add(jTextField38);
        jTextField38.setBounds(460, 270, 80, 30);

        jTextField39.setEnabled(false);
        getContentPane().add(jTextField39);
        jTextField39.setBounds(370, 270, 80, 30);
        getContentPane().add(jTextField40);
        jTextField40.setBounds(280, 270, 80, 30);
        getContentPane().add(jTextField41);
        jTextField41.setBounds(190, 270, 80, 30);
        getContentPane().add(jTextField42);
        jTextField42.setBounds(100, 270, 80, 30);
        getContentPane().add(jTextField43);
        jTextField43.setBounds(10, 270, 80, 30);
        getContentPane().add(jTextField44);
        jTextField44.setBounds(10, 300, 80, 30);
        getContentPane().add(jTextField45);
        jTextField45.setBounds(100, 300, 80, 30);
        getContentPane().add(jTextField46);
        jTextField46.setBounds(190, 300, 80, 30);
        getContentPane().add(jTextField47);
        jTextField47.setBounds(280, 300, 80, 30);

        jTextField48.setEnabled(false);
        getContentPane().add(jTextField48);
        jTextField48.setBounds(370, 300, 80, 30);

        jTextField49.setEnabled(false);
        getContentPane().add(jTextField49);
        jTextField49.setBounds(460, 300, 80, 30);

        jTextField50.setEnabled(false);
        getContentPane().add(jTextField50);
        jTextField50.setBounds(550, 300, 80, 30);

        jTextField51.setEnabled(false);
        getContentPane().add(jTextField51);
        jTextField51.setBounds(550, 330, 80, 30);

        jTextField52.setEnabled(false);
        getContentPane().add(jTextField52);
        jTextField52.setBounds(460, 330, 80, 30);

        jTextField53.setEnabled(false);
        getContentPane().add(jTextField53);
        jTextField53.setBounds(370, 330, 80, 30);
        getContentPane().add(jTextField54);
        jTextField54.setBounds(280, 330, 80, 30);
        getContentPane().add(jTextField55);
        jTextField55.setBounds(190, 330, 80, 30);
        getContentPane().add(jTextField56);
        jTextField56.setBounds(100, 330, 80, 30);
        getContentPane().add(jTextField57);
        jTextField57.setBounds(10, 330, 80, 30);

        jTextField58.setEnabled(false);
        getContentPane().add(jTextField58);
        jTextField58.setBounds(550, 360, 80, 30);

        jTextField59.setEnabled(false);
        getContentPane().add(jTextField59);
        jTextField59.setBounds(460, 360, 80, 30);

        jTextField60.setEnabled(false);
        getContentPane().add(jTextField60);
        jTextField60.setBounds(370, 360, 80, 30);
        getContentPane().add(jTextField61);
        jTextField61.setBounds(280, 360, 80, 30);
        getContentPane().add(jTextField62);
        jTextField62.setBounds(190, 360, 80, 30);
        getContentPane().add(jTextField63);
        jTextField63.setBounds(100, 360, 80, 30);
        getContentPane().add(jTextField64);
        jTextField64.setBounds(10, 360, 80, 30);

        jTextField65.setEnabled(false);
        getContentPane().add(jTextField65);
        jTextField65.setBounds(550, 390, 80, 30);

        jTextField66.setEnabled(false);
        getContentPane().add(jTextField66);
        jTextField66.setBounds(460, 390, 80, 30);

        jTextField67.setEnabled(false);
        getContentPane().add(jTextField67);
        jTextField67.setBounds(370, 390, 80, 30);
        getContentPane().add(jTextField68);
        jTextField68.setBounds(280, 390, 80, 30);
        getContentPane().add(jTextField69);
        jTextField69.setBounds(190, 390, 80, 30);
        getContentPane().add(jTextField70);
        jTextField70.setBounds(100, 390, 80, 30);
        getContentPane().add(jTextField71);
        jTextField71.setBounds(10, 390, 80, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Прибор 1", "Прибор 2", "Прибор 3", "Прибор 4", "Прибор 5", "Прибор 6", "Прибор 7", "Прибор 8" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(10, 30, 340, 26);

        jLabel8.setText("Прибор:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 6, 190, 20);

        jSlider1.setMaximum(10);
        jSlider1.setMinimum(2);
        getContentPane().add(jSlider1);
        jSlider1.setBounds(370, 20, 250, 42);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgNewCalib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgNewCalib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgNewCalib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgNewCalib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgNewCalib dialog = new DlgNewCalib(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField62;
    private javax.swing.JTextField jTextField63;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JTextField jTextField65;
    private javax.swing.JTextField jTextField66;
    private javax.swing.JTextField jTextField67;
    private javax.swing.JTextField jTextField68;
    private javax.swing.JTextField jTextField69;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField70;
    private javax.swing.JTextField jTextField71;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
