/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ams;

import ams.devices.Adam4017plus;
import ams.devices.Adam4024;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import javax.swing.JLabel;
import javax.swing.Timer;
import org.apache.log4j.Logger;

/**
 *
 * @author yaroslav
 */
public class PnlEdge extends javax.swing.JPanel implements ActionListener {
    
    static Logger logger = Logger.getLogger( PnlEdge.class);
    private final AMSApp theApp;
    Timer tmrRefresh;
    
    /**
     * Creates new form PnlEdge
     * @param app
     */
    public PnlEdge( AMSApp app) {
        theApp = app;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDev1TubTitle = new javax.swing.JLabel();
        lblDev1AnoTitle = new javax.swing.JLabel();
        lblDev2TubTitle = new javax.swing.JLabel();
        lblDev2AnoTitle = new javax.swing.JLabel();
        lblDev3TubTitle = new javax.swing.JLabel();
        lblDev3AnoTitle = new javax.swing.JLabel();
        lblDev4TubTitle = new javax.swing.JLabel();
        lblDev4AnoTitle = new javax.swing.JLabel();
        lblDev5TubTitle = new javax.swing.JLabel();
        lblDev5AnoTitle = new javax.swing.JLabel();
        lblDev6TubTitle = new javax.swing.JLabel();
        lblDev6AnoTitle = new javax.swing.JLabel();
        lblDev7TubTitle = new javax.swing.JLabel();
        lblDev7AnoTitle = new javax.swing.JLabel();
        lblDev8TubTitle = new javax.swing.JLabel();
        lblDev8AnoTitle = new javax.swing.JLabel();
        lblDev1AnoCurrent = new javax.swing.JLabel();
        lblDev1TubCurrent = new javax.swing.JLabel();
        lblDev2AnoCurrent = new javax.swing.JLabel();
        lblDev2TubCurrent = new javax.swing.JLabel();
        lblDev3AnoCurrent = new javax.swing.JLabel();
        lblDev3TubCurrent = new javax.swing.JLabel();
        lblDev4AnoCurrent = new javax.swing.JLabel();
        lblDev4TubCurrent = new javax.swing.JLabel();
        lblDev5AnoCurrent = new javax.swing.JLabel();
        lblDev5TubCurrent = new javax.swing.JLabel();
        lblDev6AnoCurrent = new javax.swing.JLabel();
        lblDev6TubCurrent = new javax.swing.JLabel();
        lblDev7AnoCurrent = new javax.swing.JLabel();
        lblDev7TubCurrent = new javax.swing.JLabel();
        lblDev8AnoCurrent = new javax.swing.JLabel();
        lblDev8TubCurrent = new javax.swing.JLabel();
        lblDev1AnoVoltage = new javax.swing.JLabel();
        lblDev1TubVoltage = new javax.swing.JLabel();
        lblDev2AnoVoltage = new javax.swing.JLabel();
        lblDev2TubVoltage = new javax.swing.JLabel();
        lblDev3AnoVoltage = new javax.swing.JLabel();
        lblDev3TubVoltage = new javax.swing.JLabel();
        lblDev4AnoVoltage = new javax.swing.JLabel();
        lblDev4TubVoltage = new javax.swing.JLabel();
        lblDev5AnoVoltage = new javax.swing.JLabel();
        lblDev5TubVoltage = new javax.swing.JLabel();
        lblDev6AnoVoltage = new javax.swing.JLabel();
        lblDev6TubVoltage = new javax.swing.JLabel();
        lblDev7AnoVoltage = new javax.swing.JLabel();
        lblDev7TubVoltage = new javax.swing.JLabel();
        lblDev8AnoVoltage = new javax.swing.JLabel();
        lblDev8TubVoltage = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setLayout(null);

        lblDev1TubTitle.setText("Прибор 1.Штенгель.");
        add(lblDev1TubTitle);
        lblDev1TubTitle.setBounds(10, 30, 160, 20);

        lblDev1AnoTitle.setText("Прибор 1.Анод.");
        add(lblDev1AnoTitle);
        lblDev1AnoTitle.setBounds(10, 10, 160, 20);

        lblDev2TubTitle.setText("Прибор 2.Штенгель.");
        add(lblDev2TubTitle);
        lblDev2TubTitle.setBounds(10, 100, 160, 20);

        lblDev2AnoTitle.setText("Прибор 2.Анод.");
        add(lblDev2AnoTitle);
        lblDev2AnoTitle.setBounds(10, 80, 160, 20);

        lblDev3TubTitle.setText("Прибор 3.Штенгель.");
        add(lblDev3TubTitle);
        lblDev3TubTitle.setBounds(10, 170, 160, 20);

        lblDev3AnoTitle.setText("Прибор 3.Анод.");
        add(lblDev3AnoTitle);
        lblDev3AnoTitle.setBounds(10, 150, 160, 20);

        lblDev4TubTitle.setText("Прибор 4.Штенгель.");
        add(lblDev4TubTitle);
        lblDev4TubTitle.setBounds(10, 240, 160, 20);

        lblDev4AnoTitle.setText("Прибор 4.Анод.");
        add(lblDev4AnoTitle);
        lblDev4AnoTitle.setBounds(10, 220, 160, 20);

        lblDev5TubTitle.setText("Прибор 5.Штенгель.");
        add(lblDev5TubTitle);
        lblDev5TubTitle.setBounds(10, 310, 160, 20);

        lblDev5AnoTitle.setText("Прибор 5.Анод.");
        add(lblDev5AnoTitle);
        lblDev5AnoTitle.setBounds(10, 290, 160, 20);

        lblDev6TubTitle.setText("Прибор 6.Штенгель.");
        add(lblDev6TubTitle);
        lblDev6TubTitle.setBounds(10, 380, 160, 20);

        lblDev6AnoTitle.setText("Прибор 6.Анод.");
        add(lblDev6AnoTitle);
        lblDev6AnoTitle.setBounds(10, 360, 160, 20);

        lblDev7TubTitle.setText("Прибор 7.Штенгель.");
        add(lblDev7TubTitle);
        lblDev7TubTitle.setBounds(10, 450, 160, 20);

        lblDev7AnoTitle.setText("Прибор 7.Анод.");
        add(lblDev7AnoTitle);
        lblDev7AnoTitle.setBounds(10, 430, 160, 20);

        lblDev8TubTitle.setText("Прибор 8.Штенгель.");
        add(lblDev8TubTitle);
        lblDev8TubTitle.setBounds(10, 520, 160, 20);

        lblDev8AnoTitle.setText("Прибор 8.Анод.");
        add(lblDev8AnoTitle);
        lblDev8AnoTitle.setBounds(10, 500, 160, 20);

        lblDev1AnoCurrent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev1AnoCurrent.setText("-");
        add(lblDev1AnoCurrent);
        lblDev1AnoCurrent.setBounds(190, 10, 70, 20);

        lblDev1TubCurrent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev1TubCurrent.setText("-");
        add(lblDev1TubCurrent);
        lblDev1TubCurrent.setBounds(190, 30, 70, 20);

        lblDev2AnoCurrent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev2AnoCurrent.setText("-");
        add(lblDev2AnoCurrent);
        lblDev2AnoCurrent.setBounds(190, 80, 70, 20);

        lblDev2TubCurrent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev2TubCurrent.setText("-");
        add(lblDev2TubCurrent);
        lblDev2TubCurrent.setBounds(190, 100, 70, 20);

        lblDev3AnoCurrent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev3AnoCurrent.setText("-");
        add(lblDev3AnoCurrent);
        lblDev3AnoCurrent.setBounds(190, 150, 70, 20);

        lblDev3TubCurrent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev3TubCurrent.setText("-");
        add(lblDev3TubCurrent);
        lblDev3TubCurrent.setBounds(190, 170, 70, 20);

        lblDev4AnoCurrent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev4AnoCurrent.setText("-");
        add(lblDev4AnoCurrent);
        lblDev4AnoCurrent.setBounds(190, 220, 70, 20);

        lblDev4TubCurrent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev4TubCurrent.setText("-");
        add(lblDev4TubCurrent);
        lblDev4TubCurrent.setBounds(190, 240, 70, 20);

        lblDev5AnoCurrent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev5AnoCurrent.setText("-");
        add(lblDev5AnoCurrent);
        lblDev5AnoCurrent.setBounds(190, 290, 70, 20);

        lblDev5TubCurrent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev5TubCurrent.setText("-");
        add(lblDev5TubCurrent);
        lblDev5TubCurrent.setBounds(190, 310, 70, 20);

        lblDev6AnoCurrent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev6AnoCurrent.setText("-");
        add(lblDev6AnoCurrent);
        lblDev6AnoCurrent.setBounds(190, 360, 70, 20);

        lblDev6TubCurrent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev6TubCurrent.setText("-");
        add(lblDev6TubCurrent);
        lblDev6TubCurrent.setBounds(190, 380, 70, 20);

        lblDev7AnoCurrent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev7AnoCurrent.setText("-");
        add(lblDev7AnoCurrent);
        lblDev7AnoCurrent.setBounds(190, 430, 70, 20);

        lblDev7TubCurrent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev7TubCurrent.setText("-");
        add(lblDev7TubCurrent);
        lblDev7TubCurrent.setBounds(190, 450, 70, 20);

        lblDev8AnoCurrent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev8AnoCurrent.setText("-");
        add(lblDev8AnoCurrent);
        lblDev8AnoCurrent.setBounds(190, 500, 70, 20);

        lblDev8TubCurrent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev8TubCurrent.setText("-");
        add(lblDev8TubCurrent);
        lblDev8TubCurrent.setBounds(190, 520, 70, 20);

        lblDev1AnoVoltage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev1AnoVoltage.setText("-");
        add(lblDev1AnoVoltage);
        lblDev1AnoVoltage.setBounds(280, 10, 70, 20);

        lblDev1TubVoltage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev1TubVoltage.setText("-");
        add(lblDev1TubVoltage);
        lblDev1TubVoltage.setBounds(280, 30, 70, 20);

        lblDev2AnoVoltage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev2AnoVoltage.setText("-");
        add(lblDev2AnoVoltage);
        lblDev2AnoVoltage.setBounds(280, 80, 70, 20);

        lblDev2TubVoltage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev2TubVoltage.setText("-");
        add(lblDev2TubVoltage);
        lblDev2TubVoltage.setBounds(280, 100, 70, 20);

        lblDev3AnoVoltage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev3AnoVoltage.setText("-");
        add(lblDev3AnoVoltage);
        lblDev3AnoVoltage.setBounds(280, 150, 70, 20);

        lblDev3TubVoltage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev3TubVoltage.setText("-");
        add(lblDev3TubVoltage);
        lblDev3TubVoltage.setBounds(280, 170, 70, 20);

        lblDev4AnoVoltage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev4AnoVoltage.setText("-");
        add(lblDev4AnoVoltage);
        lblDev4AnoVoltage.setBounds(280, 220, 70, 20);

        lblDev4TubVoltage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev4TubVoltage.setText("-");
        add(lblDev4TubVoltage);
        lblDev4TubVoltage.setBounds(280, 240, 70, 20);

        lblDev5AnoVoltage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev5AnoVoltage.setText("-");
        add(lblDev5AnoVoltage);
        lblDev5AnoVoltage.setBounds(280, 290, 70, 20);

        lblDev5TubVoltage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev5TubVoltage.setText("-");
        add(lblDev5TubVoltage);
        lblDev5TubVoltage.setBounds(280, 310, 70, 20);

        lblDev6AnoVoltage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev6AnoVoltage.setText("-");
        add(lblDev6AnoVoltage);
        lblDev6AnoVoltage.setBounds(280, 360, 70, 20);

        lblDev6TubVoltage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev6TubVoltage.setText("-");
        add(lblDev6TubVoltage);
        lblDev6TubVoltage.setBounds(280, 380, 70, 20);

        lblDev7AnoVoltage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev7AnoVoltage.setText("-");
        add(lblDev7AnoVoltage);
        lblDev7AnoVoltage.setBounds(280, 430, 70, 20);

        lblDev7TubVoltage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev7TubVoltage.setText("-");
        add(lblDev7TubVoltage);
        lblDev7TubVoltage.setBounds(280, 450, 70, 20);

        lblDev8AnoVoltage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev8AnoVoltage.setText("-");
        add(lblDev8AnoVoltage);
        lblDev8AnoVoltage.setBounds(280, 500, 70, 20);

        lblDev8TubVoltage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev8TubVoltage.setText("-");
        add(lblDev8TubVoltage);
        lblDev8TubVoltage.setBounds(280, 520, 70, 20);

        btnSave.setText("Сохранить");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(70, 570, 260, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    public void startRefreshTimer() {
        tmrRefresh = new Timer( 1000, this);
        tmrRefresh.start();
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        Adam4017plus adcC = theApp.GetDevManager_0_a().GetADCCurrent();
        int nAdcC_Channel = 0;
        Adam4017plus adcV = theApp.GetDevManager_0_a().GetADCVoltage();
        int nAdcV_Channel = 0;
        
        JLabel lblCurrent = lblDev1AnoCurrent;
        JLabel lblVoltage = lblDev1AnoVoltage;
                
        AMSDeviceManager mngr = theApp.GetDevManager_0_a();
        
        for( int i=0; i < 16; i++) {
            switch( i) {
                case  0: mngr = theApp.GetDevManager_0_a(); lblCurrent = lblDev1AnoCurrent; lblVoltage = lblDev1AnoVoltage; break;
                case  1: mngr = theApp.GetDevManager_0_t(); lblCurrent = lblDev1TubCurrent; lblVoltage = lblDev1TubVoltage; break;
                    
                case  2: mngr = theApp.GetDevManager_1_a(); lblCurrent = lblDev2AnoCurrent; lblVoltage = lblDev2AnoVoltage; break;
                case  3: mngr = theApp.GetDevManager_1_t(); lblCurrent = lblDev2TubCurrent; lblVoltage = lblDev2TubVoltage; break;
                    
                case  4: mngr = theApp.GetDevManager_2_a(); lblCurrent = lblDev3AnoCurrent; lblVoltage = lblDev3AnoVoltage; break;
                case  5: mngr = theApp.GetDevManager_2_t(); lblCurrent = lblDev3TubCurrent; lblVoltage = lblDev3TubVoltage; break;
                    
                case  6: mngr = theApp.GetDevManager_3_a(); lblCurrent = lblDev4AnoCurrent; lblVoltage = lblDev4AnoVoltage; break;
                case  7: mngr = theApp.GetDevManager_3_t(); lblCurrent = lblDev4TubCurrent; lblVoltage = lblDev4TubVoltage; break;
                    
                case  8: mngr = theApp.GetDevManager_4_a(); lblCurrent = lblDev5AnoCurrent; lblVoltage = lblDev5AnoVoltage; break;
                case  9: mngr = theApp.GetDevManager_4_t(); lblCurrent = lblDev5TubCurrent; lblVoltage = lblDev5TubVoltage; break;
                    
                case 10: mngr = theApp.GetDevManager_5_a(); lblCurrent = lblDev6AnoCurrent; lblVoltage = lblDev6AnoVoltage; break;
                case 11: mngr = theApp.GetDevManager_5_t(); lblCurrent = lblDev6TubCurrent; lblVoltage = lblDev6TubVoltage; break;
                    
                case 12: mngr = theApp.GetDevManager_6_a(); lblCurrent = lblDev7AnoCurrent; lblVoltage = lblDev7AnoVoltage; break;
                case 13: mngr = theApp.GetDevManager_6_t(); lblCurrent = lblDev7TubCurrent; lblVoltage = lblDev7TubVoltage; break;
                    
                case 14: mngr = theApp.GetDevManager_7_a(); lblCurrent = lblDev8AnoCurrent; lblVoltage = lblDev8AnoVoltage; break;
                case 15: mngr = theApp.GetDevManager_7_t(); lblCurrent = lblDev8TubCurrent; lblVoltage = lblDev8TubVoltage; break;
            }
        
            if( mngr != null) {
                //ТОК
                adcC = mngr.GetADCCurrent();
                nAdcC_Channel = mngr.GetAdcCurrentChannel();
                double dblCurrentValue = 0.;
                try {
                    dblCurrentValue = adcC.GetAveragerChannel( nAdcC_Channel).GetAverage();
                } catch (Exception ex) {
                    logger.error( "При получении осреднителя значений для канала АЦП произошёл Exception", ex);
                }
                lblCurrent.setText( "" + String.format( "%.3f", dblCurrentValue * 1000.) + "mcA");
                if( mngr.GetEnabled()) {
                    lblCurrent.setForeground( Color.red);
                }
                else {
                    lblCurrent.setForeground( Color.green);
                    Font oldFont = lblCurrent.getFont();
                    if( !oldFont.isBold()) {
                        Font newFont = new Font( oldFont.getName(), oldFont.getStyle() + Font.BOLD, oldFont.getSize());
                        lblCurrent.setFont( newFont);
                    }
                }
                
                //НАПРЯЖЕНИЕ
                adcV = mngr.GetADCVoltage();
                nAdcV_Channel = mngr.GetAdcVoltageChannel();
                double dblVoltageValue = 0.;
                try {
                    dblVoltageValue = adcV.GetAveragerChannel( nAdcV_Channel).GetAverage();
                } catch (Exception ex) {
                    logger.error( "При получении осреднителя значений для канала АЦП произошёл Exception", ex);
                }
                lblVoltage.setText( "" + String.format( "%.3f", dblVoltageValue) + "V");
                if( mngr.GetEnabled()) {
                    lblVoltage.setForeground( Color.red);
                }
                else {
                    lblVoltage.setForeground( Color.green);
                    Font oldFont = lblVoltage.getFont();
                    if( !oldFont.isBold()) {
                        Font newFont = new Font( oldFont.getName(), oldFont.getStyle() + Font.BOLD, oldFont.getSize());
                        lblVoltage.setFont( newFont);
                    }
                }       
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblDev1AnoCurrent;
    private javax.swing.JLabel lblDev1AnoTitle;
    private javax.swing.JLabel lblDev1AnoVoltage;
    private javax.swing.JLabel lblDev1TubCurrent;
    private javax.swing.JLabel lblDev1TubTitle;
    private javax.swing.JLabel lblDev1TubVoltage;
    private javax.swing.JLabel lblDev2AnoCurrent;
    private javax.swing.JLabel lblDev2AnoTitle;
    private javax.swing.JLabel lblDev2AnoVoltage;
    private javax.swing.JLabel lblDev2TubCurrent;
    private javax.swing.JLabel lblDev2TubTitle;
    private javax.swing.JLabel lblDev2TubVoltage;
    private javax.swing.JLabel lblDev3AnoCurrent;
    private javax.swing.JLabel lblDev3AnoTitle;
    private javax.swing.JLabel lblDev3AnoVoltage;
    private javax.swing.JLabel lblDev3TubCurrent;
    private javax.swing.JLabel lblDev3TubTitle;
    private javax.swing.JLabel lblDev3TubVoltage;
    private javax.swing.JLabel lblDev4AnoCurrent;
    private javax.swing.JLabel lblDev4AnoTitle;
    private javax.swing.JLabel lblDev4AnoVoltage;
    private javax.swing.JLabel lblDev4TubCurrent;
    private javax.swing.JLabel lblDev4TubTitle;
    private javax.swing.JLabel lblDev4TubVoltage;
    private javax.swing.JLabel lblDev5AnoCurrent;
    private javax.swing.JLabel lblDev5AnoTitle;
    private javax.swing.JLabel lblDev5AnoVoltage;
    private javax.swing.JLabel lblDev5TubCurrent;
    private javax.swing.JLabel lblDev5TubTitle;
    private javax.swing.JLabel lblDev5TubVoltage;
    private javax.swing.JLabel lblDev6AnoCurrent;
    private javax.swing.JLabel lblDev6AnoTitle;
    private javax.swing.JLabel lblDev6AnoVoltage;
    private javax.swing.JLabel lblDev6TubCurrent;
    private javax.swing.JLabel lblDev6TubTitle;
    private javax.swing.JLabel lblDev6TubVoltage;
    private javax.swing.JLabel lblDev7AnoCurrent;
    private javax.swing.JLabel lblDev7AnoTitle;
    private javax.swing.JLabel lblDev7AnoVoltage;
    private javax.swing.JLabel lblDev7TubCurrent;
    private javax.swing.JLabel lblDev7TubTitle;
    private javax.swing.JLabel lblDev7TubVoltage;
    private javax.swing.JLabel lblDev8AnoCurrent;
    private javax.swing.JLabel lblDev8AnoTitle;
    private javax.swing.JLabel lblDev8AnoVoltage;
    private javax.swing.JLabel lblDev8TubCurrent;
    private javax.swing.JLabel lblDev8TubTitle;
    private javax.swing.JLabel lblDev8TubVoltage;
    // End of variables declaration//GEN-END:variables

}
