/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ams;

import ams.devices.Adam4017plus;
import ams.devices.Adam4024;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.Timer;
import org.apache.log4j.Logger;

/**
 *
 * @author yaroslav
 */
public class PnlProcessing extends javax.swing.JPanel implements ActionListener  {

    static Logger logger = Logger.getLogger( PnlProcessing.class);
    
    Timer tmrRefresh;
    
    public double m_dblDacAno1_0;
    public double m_dblDacAno1_1;
    /*public double m_dblDacAno1_2;
    public double m_dblDacAno1_3;
    public double m_dblDacAno2_0;
    public double m_dblDacAno2_1;
    public double m_dblDacAno2_2;
    public double m_dblDacAno2_3;
    public double m_dblDacTub1_0;
    public double m_dblDacTub1_1;
    public double m_dblDacTub1_2;
    public double m_dblDacTub1_3;    
    public double m_dblDacTub2_0;
    public double m_dblDacTub2_1;
    public double m_dblDacTub2_2;
    public double m_dblDacTub2_3;*/
    
            
    private final AMSApp theApp;
    /**
     * Creates new form PnlProcessing
     */
    public PnlProcessing( AMSApp app) {
        theApp = app;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField13 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jTextField14 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jTextField16 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        edtDesiredVoltageAno1_0 = new javax.swing.JTextField();
        btnApplyAno1_0 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        edtDesiredVoltageAno1_1 = new javax.swing.JTextField();
        btnApplyAno1_1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        edtDesiredVoltageAno1_2 = new javax.swing.JTextField();
        btnApplyAno1_2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        edtDesiredVoltageAno1_3 = new javax.swing.JTextField();
        btnApplyAno1_3 = new javax.swing.JButton();
        edtDesiredVoltageAno2_3 = new javax.swing.JTextField();
        btnApplyAno2_3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        edtDesiredVoltageAno2_0 = new javax.swing.JTextField();
        btnApplyAno2_1 = new javax.swing.JButton();
        edtDesiredVoltageAno2_1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnApplyAno2_0 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnApplyAno2_2 = new javax.swing.JButton();
        edtDesiredVoltageAno2_2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        edtDesiredVoltageTub1_2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnApplyTub1_2 = new javax.swing.JButton();
        edtDesiredVoltageTub1_3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        edtDesiredVoltageTub1_1 = new javax.swing.JTextField();
        btnApplyTub1_0 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnApplyTub1_3 = new javax.swing.JButton();
        btnApplyTub1_1 = new javax.swing.JButton();
        edtDesiredVoltageTub1_0 = new javax.swing.JTextField();
        edtDesiredVoltageTub2_2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnApplyTub2_2 = new javax.swing.JButton();
        edtDesiredVoltageTub2_3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        edtDesiredVoltageTub2_1 = new javax.swing.JTextField();
        btnApplyTub2_0 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        btnApplyTub2_3 = new javax.swing.JButton();
        btnApplyTub2_1 = new javax.swing.JButton();
        edtDesiredVoltageTub2_0 = new javax.swing.JTextField();
        lblCurrentOutputAno1_0 = new javax.swing.JLabel();
        lblCurrentOutputAno1_1 = new javax.swing.JLabel();
        lblCurrentOutputAno1_2 = new javax.swing.JLabel();
        lblCurrentOutputAno1_3 = new javax.swing.JLabel();
        lblCurrentOutputAno2_0 = new javax.swing.JLabel();
        lblCurrentOutputAno2_1 = new javax.swing.JLabel();
        lblCurrentOutputAno2_2 = new javax.swing.JLabel();
        lblCurrentOutputAno2_3 = new javax.swing.JLabel();
        lblCurrentOutputTub1_0 = new javax.swing.JLabel();
        lblCurrentOutputTub1_1 = new javax.swing.JLabel();
        lblCurrentOutputTub1_2 = new javax.swing.JLabel();
        lblCurrentOutputTub1_3 = new javax.swing.JLabel();
        lblCurrentOutputTub2_0 = new javax.swing.JLabel();
        lblCurrentOutputTub2_1 = new javax.swing.JLabel();
        lblCurrentOutputTub2_2 = new javax.swing.JLabel();
        lblCurrentOutputTub2_3 = new javax.swing.JLabel();

        jTextField13.setText("-");

        jLabel13.setText("Напряжение на DAC03.2");

        jLabel14.setText("Напряжение на DAC03.3");

        jButton13.setText("Применить");

        jTextField14.setText("-");

        jLabel15.setText("Напряжение на DAC03.1");

        jTextField15.setText("-");

        jButton14.setText("Применить");

        jLabel16.setText("Напряжение на DAC03.0");

        jButton15.setText("Применить");

        jButton16.setText("Применить");

        jTextField16.setText("-");

        jLabel1.setText("U на DAC_03.0:");

        edtDesiredVoltageAno1_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtDesiredVoltageAno1_0.setText("-");

        btnApplyAno1_0.setText("Применить");
        btnApplyAno1_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyAno1_0ActionPerformed(evt);
            }
        });

        jLabel2.setText("U на DAC_03.1:");

        edtDesiredVoltageAno1_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtDesiredVoltageAno1_1.setText("-");

        btnApplyAno1_1.setText("Применить");
        btnApplyAno1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyAno1_1ActionPerformed(evt);
            }
        });

        jLabel3.setText("U на DAC_03.2:");
        jLabel3.setToolTipText("");

        edtDesiredVoltageAno1_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtDesiredVoltageAno1_2.setText("-");

        btnApplyAno1_2.setText("Применить");
        btnApplyAno1_2.setEnabled(false);

        jLabel4.setText("U на DAC_03.3:");

        edtDesiredVoltageAno1_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtDesiredVoltageAno1_3.setText("-");

        btnApplyAno1_3.setText("Применить");
        btnApplyAno1_3.setEnabled(false);

        edtDesiredVoltageAno2_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtDesiredVoltageAno2_3.setText("-");

        btnApplyAno2_3.setText("Применить");
        btnApplyAno2_3.setEnabled(false);

        jLabel5.setText("U на DAC_04.0:");

        edtDesiredVoltageAno2_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtDesiredVoltageAno2_0.setText("-");

        btnApplyAno2_1.setText("Применить");
        btnApplyAno2_1.setEnabled(false);

        edtDesiredVoltageAno2_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtDesiredVoltageAno2_1.setText("-");

        jLabel6.setText("U на DAC_04.1:");

        btnApplyAno2_0.setText("Применить");
        btnApplyAno2_0.setEnabled(false);

        jLabel7.setText("U на DAC_04.3:");

        btnApplyAno2_2.setText("Применить");
        btnApplyAno2_2.setEnabled(false);

        edtDesiredVoltageAno2_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtDesiredVoltageAno2_2.setText("-");

        jLabel8.setText("U на DAC_04.2:");
        jLabel8.setToolTipText("");

        edtDesiredVoltageTub1_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtDesiredVoltageTub1_2.setText("-");

        jLabel9.setText("U на DAC_13.2:");

        jLabel10.setText("U на DAC_13.3:");

        btnApplyTub1_2.setText("Применить");
        btnApplyTub1_2.setEnabled(false);

        edtDesiredVoltageTub1_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtDesiredVoltageTub1_3.setText("-");

        jLabel11.setText("U на DAC_13.1:");

        edtDesiredVoltageTub1_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtDesiredVoltageTub1_1.setText("-");

        btnApplyTub1_0.setText("Применить");
        btnApplyTub1_0.setEnabled(false);

        jLabel12.setText("U на DAC_13.0:");

        btnApplyTub1_3.setText("Применить");
        btnApplyTub1_3.setEnabled(false);

        btnApplyTub1_1.setText("Применить");
        btnApplyTub1_1.setEnabled(false);

        edtDesiredVoltageTub1_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtDesiredVoltageTub1_0.setText("-");

        edtDesiredVoltageTub2_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtDesiredVoltageTub2_2.setText("-");

        jLabel17.setText("U на DAC_14.2:");

        jLabel18.setText("U на DAC_14.3:");

        btnApplyTub2_2.setText("Применить");
        btnApplyTub2_2.setEnabled(false);

        edtDesiredVoltageTub2_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtDesiredVoltageTub2_3.setText("-");

        jLabel19.setText("U на DAC_14.1:");

        edtDesiredVoltageTub2_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtDesiredVoltageTub2_1.setText("-");

        btnApplyTub2_0.setText("Применить");
        btnApplyTub2_0.setEnabled(false);

        jLabel20.setText("U на DAC_14.0:");

        btnApplyTub2_3.setText("Применить");
        btnApplyTub2_3.setEnabled(false);

        btnApplyTub2_1.setText("Применить");
        btnApplyTub2_1.setEnabled(false);

        edtDesiredVoltageTub2_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtDesiredVoltageTub2_0.setText("-");

        lblCurrentOutputAno1_0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentOutputAno1_0.setText("-");
        lblCurrentOutputAno1_0.setBorder(null);

        lblCurrentOutputAno1_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentOutputAno1_1.setText("-");
        lblCurrentOutputAno1_1.setBorder(null);

        lblCurrentOutputAno1_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentOutputAno1_2.setText("-");
        lblCurrentOutputAno1_2.setBorder(null);

        lblCurrentOutputAno1_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentOutputAno1_3.setText("-");
        lblCurrentOutputAno1_3.setBorder(null);

        lblCurrentOutputAno2_0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentOutputAno2_0.setText("-");
        lblCurrentOutputAno2_0.setBorder(null);

        lblCurrentOutputAno2_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentOutputAno2_1.setText("-");
        lblCurrentOutputAno2_1.setBorder(null);

        lblCurrentOutputAno2_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentOutputAno2_2.setText("-");
        lblCurrentOutputAno2_2.setBorder(null);

        lblCurrentOutputAno2_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentOutputAno2_3.setText("-");
        lblCurrentOutputAno2_3.setBorder(null);

        lblCurrentOutputTub1_0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentOutputTub1_0.setText("-");
        lblCurrentOutputTub1_0.setBorder(null);

        lblCurrentOutputTub1_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentOutputTub1_1.setText("-");
        lblCurrentOutputTub1_1.setBorder(null);

        lblCurrentOutputTub1_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentOutputTub1_2.setText("-");
        lblCurrentOutputTub1_2.setBorder(null);

        lblCurrentOutputTub1_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentOutputTub1_3.setText("-");
        lblCurrentOutputTub1_3.setBorder(null);

        lblCurrentOutputTub2_0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentOutputTub2_0.setText("-");
        lblCurrentOutputTub2_0.setBorder(null);

        lblCurrentOutputTub2_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentOutputTub2_1.setText("-");
        lblCurrentOutputTub2_1.setBorder(null);

        lblCurrentOutputTub2_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentOutputTub2_2.setText("-");
        lblCurrentOutputTub2_2.setBorder(null);

        lblCurrentOutputTub2_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentOutputTub2_3.setText("-");
        lblCurrentOutputTub2_3.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCurrentOutputAno1_0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtDesiredVoltageAno1_0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnApplyAno1_0))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCurrentOutputAno1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edtDesiredVoltageAno1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnApplyAno1_1)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCurrentOutputAno1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(edtDesiredVoltageAno1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnApplyAno1_2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCurrentOutputAno1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(edtDesiredVoltageAno1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnApplyAno1_3)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCurrentOutputAno2_0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(edtDesiredVoltageAno2_0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnApplyAno2_0))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCurrentOutputAno2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edtDesiredVoltageAno2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnApplyAno2_1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCurrentOutputAno2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(edtDesiredVoltageAno2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnApplyAno2_2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCurrentOutputAno2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edtDesiredVoltageAno2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnApplyAno2_3)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCurrentOutputTub1_0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(edtDesiredVoltageTub1_0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnApplyTub1_0))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCurrentOutputTub1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edtDesiredVoltageTub1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnApplyTub1_1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCurrentOutputTub1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(edtDesiredVoltageTub1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnApplyTub1_2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCurrentOutputTub1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edtDesiredVoltageTub1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnApplyTub1_3)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCurrentOutputTub2_0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(edtDesiredVoltageTub2_0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnApplyTub2_0))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCurrentOutputTub2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edtDesiredVoltageTub2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnApplyTub2_1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCurrentOutputTub2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(edtDesiredVoltageTub2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnApplyTub2_2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCurrentOutputTub2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edtDesiredVoltageTub2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnApplyTub2_3))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edtDesiredVoltageAno1_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApplyAno1_0)
                    .addComponent(lblCurrentOutputAno1_0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edtDesiredVoltageAno1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApplyAno1_1)
                    .addComponent(lblCurrentOutputAno1_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edtDesiredVoltageAno1_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApplyAno1_2)
                    .addComponent(lblCurrentOutputAno1_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(edtDesiredVoltageAno1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApplyAno1_3)
                    .addComponent(lblCurrentOutputAno1_3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(edtDesiredVoltageAno2_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApplyAno2_0)
                    .addComponent(lblCurrentOutputAno2_0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(edtDesiredVoltageAno2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApplyAno2_1)
                    .addComponent(lblCurrentOutputAno2_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(edtDesiredVoltageAno2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApplyAno2_2)
                    .addComponent(lblCurrentOutputAno2_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(edtDesiredVoltageAno2_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApplyAno2_3)
                    .addComponent(lblCurrentOutputAno2_3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(edtDesiredVoltageTub1_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApplyTub1_0)
                    .addComponent(lblCurrentOutputTub1_0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(edtDesiredVoltageTub1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApplyTub1_1)
                    .addComponent(lblCurrentOutputTub1_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(edtDesiredVoltageTub1_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApplyTub1_2)
                    .addComponent(lblCurrentOutputTub1_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(edtDesiredVoltageTub1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApplyTub1_3)
                    .addComponent(lblCurrentOutputTub1_3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(edtDesiredVoltageTub2_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApplyTub2_0)
                    .addComponent(lblCurrentOutputTub2_0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(edtDesiredVoltageTub2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApplyTub2_1)
                    .addComponent(lblCurrentOutputTub2_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(edtDesiredVoltageTub2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApplyTub2_2)
                    .addComponent(lblCurrentOutputTub2_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(edtDesiredVoltageTub2_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApplyTub2_3)
                    .addComponent(lblCurrentOutputTub2_3))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jLabel5.getAccessibleContext().setAccessibleName("Напряжение на DAC04.0");
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplyAno1_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyAno1_0ActionPerformed
        Double dblVal;
        try {
            dblVal = new Double( edtDesiredVoltageAno1_0.getText());
        }
        catch ( NumberFormatException e) {
            logger.warn( "Caught NumberFormatException!", e);
            edtDesiredVoltageAno1_0.setText( lblCurrentOutputAno1_0.getText());
            return;
        }
        
        if( dblVal >= AMSConstants.DAC_MAX_OUTPUT_VOLTAGE) {
            dblVal = AMSConstants.DAC_MAX_OUTPUT_VOLTAGE;
            edtDesiredVoltageAno1_0.setText( "" + String.format( "%.3f", dblVal));
        }
        if( dblVal <= AMSConstants.DAC_MIN_OUTPUT_VOLTAGE) {
            dblVal = AMSConstants.DAC_MIN_OUTPUT_VOLTAGE;
            edtDesiredVoltageAno1_0.setText( "" + String.format( "%.3f", dblVal));
        }
        
        m_dblDacAno1_0 = dblVal;
        if( theApp.GetMainSwitcher() == true) {
            try {
                theApp.m_devicesSet.GetDAC( AMSConstants.DAC1).QueueSetChannelOutputValueCommand( 0, dblVal);
            }
            catch( Exception e) {
                logger.error( "При выставке напряжения на ЦАП, произошла исключительная ситуация", e);
            }
        }
        else {
            logger.warn( "btnApplyAno1_1ActionPerformed: применение введённого напряжения заблокировано рубильником!");
        }        
    }//GEN-LAST:event_btnApplyAno1_0ActionPerformed

    private void btnApplyAno1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyAno1_1ActionPerformed
        
        
        Double dblVal = new Double( edtDesiredVoltageAno1_1.getText());
        if( dblVal >= AMSConstants.DAC_MAX_OUTPUT_VOLTAGE) {
            dblVal = AMSConstants.DAC_MAX_OUTPUT_VOLTAGE;
            edtDesiredVoltageAno1_1.setText( "" + String.format( "%.3f", dblVal));
        }
        if( dblVal <= AMSConstants.DAC_MIN_OUTPUT_VOLTAGE) {
            dblVal = AMSConstants.DAC_MIN_OUTPUT_VOLTAGE;
            edtDesiredVoltageAno1_1.setText( "" + String.format( "%.3f", dblVal));
        }
        
        m_dblDacAno1_1 = dblVal;
        
        if( theApp.GetMainSwitcher() == true) {
            try {
                theApp.m_devicesSet.GetDAC( AMSConstants.DAC1).QueueSetChannelOutputValueCommand( 1, dblVal);
            }
            catch( Exception e) {
                logger.error( "При выставке напряжения на ЦАП, произошла исключительная ситуация", e);
            }
        }
        else {
            logger.warn( "btnApplyAno1_1ActionPerformed: применение введённого напряжения заблокировано рубильником!");
        }
    }//GEN-LAST:event_btnApplyAno1_1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyAno1_0;
    private javax.swing.JButton btnApplyAno1_1;
    private javax.swing.JButton btnApplyAno1_2;
    private javax.swing.JButton btnApplyAno1_3;
    private javax.swing.JButton btnApplyAno2_0;
    private javax.swing.JButton btnApplyAno2_1;
    private javax.swing.JButton btnApplyAno2_2;
    private javax.swing.JButton btnApplyAno2_3;
    private javax.swing.JButton btnApplyTub1_0;
    private javax.swing.JButton btnApplyTub1_1;
    private javax.swing.JButton btnApplyTub1_2;
    private javax.swing.JButton btnApplyTub1_3;
    private javax.swing.JButton btnApplyTub2_0;
    private javax.swing.JButton btnApplyTub2_1;
    private javax.swing.JButton btnApplyTub2_2;
    private javax.swing.JButton btnApplyTub2_3;
    private javax.swing.JTextField edtDesiredVoltageAno1_0;
    private javax.swing.JTextField edtDesiredVoltageAno1_1;
    private javax.swing.JTextField edtDesiredVoltageAno1_2;
    private javax.swing.JTextField edtDesiredVoltageAno1_3;
    private javax.swing.JTextField edtDesiredVoltageAno2_0;
    private javax.swing.JTextField edtDesiredVoltageAno2_1;
    private javax.swing.JTextField edtDesiredVoltageAno2_2;
    private javax.swing.JTextField edtDesiredVoltageAno2_3;
    private javax.swing.JTextField edtDesiredVoltageTub1_0;
    private javax.swing.JTextField edtDesiredVoltageTub1_1;
    private javax.swing.JTextField edtDesiredVoltageTub1_2;
    private javax.swing.JTextField edtDesiredVoltageTub1_3;
    private javax.swing.JTextField edtDesiredVoltageTub2_0;
    private javax.swing.JTextField edtDesiredVoltageTub2_1;
    private javax.swing.JTextField edtDesiredVoltageTub2_2;
    private javax.swing.JTextField edtDesiredVoltageTub2_3;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JLabel lblCurrentOutputAno1_0;
    private javax.swing.JLabel lblCurrentOutputAno1_1;
    private javax.swing.JLabel lblCurrentOutputAno1_2;
    private javax.swing.JLabel lblCurrentOutputAno1_3;
    private javax.swing.JLabel lblCurrentOutputAno2_0;
    private javax.swing.JLabel lblCurrentOutputAno2_1;
    private javax.swing.JLabel lblCurrentOutputAno2_2;
    private javax.swing.JLabel lblCurrentOutputAno2_3;
    private javax.swing.JLabel lblCurrentOutputTub1_0;
    private javax.swing.JLabel lblCurrentOutputTub1_1;
    private javax.swing.JLabel lblCurrentOutputTub1_2;
    private javax.swing.JLabel lblCurrentOutputTub1_3;
    private javax.swing.JLabel lblCurrentOutputTub2_0;
    private javax.swing.JLabel lblCurrentOutputTub2_1;
    private javax.swing.JLabel lblCurrentOutputTub2_2;
    private javax.swing.JLabel lblCurrentOutputTub2_3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        Adam4024 dac = theApp.GetDevManager_0_a().GetDAC();
        int nDacChannel = 0;
        
        JLabel lblDac = lblCurrentOutputAno1_0;        
        AMSDeviceManager mngr = theApp.GetDevManager_0_a();
        
        for( int i=0; i < 2; i++) {
            switch( i) {
                case  0: mngr = theApp.GetDevManager_0_a(); lblDac = lblCurrentOutputAno1_0; break;
                case  1: mngr = theApp.GetDevManager_0_t(); lblDac = lblCurrentOutputAno1_1; break;
                
                /*
                case  0: mngr = theApp.GetDevManager_0_a(); lblDac = lblCurrentOutputAno1_0; break;
                case  1: mngr = theApp.GetDevManager_0_t(); lblDac = lblCurrentOutputTub1_0; break;
                    
                case  3: mngr = theApp.GetDevManager_1_a(); lblDac = lblCurrentOutputAno1_1; break;
                case  4: mngr = theApp.GetDevManager_1_t(); lblDac = lblCurrentOutputTub1_1; break;
                    
                case  5: mngr = theApp.GetDevManager_2_a(); lblDac = lblCurrentOutputAno1_2; break;
                case  6: mngr = theApp.GetDevManager_2_t(); lblDac = lblCurrentOutputTub1_2; break;
                    
                case  7: mngr = theApp.GetDevManager_3_a(); lblDac = lblCurrentOutputAno1_3; break;
                case  8: mngr = theApp.GetDevManager_3_t(); lblDac = lblCurrentOutputTub1_3; break;
                    
                case  9: mngr = theApp.GetDevManager_4_a(); lblDac = lblCurrentOutputAno2_0; break;
                case 10: mngr = theApp.GetDevManager_4_t(); lblDac = lblCurrentOutputTub2_0; break;
                    
                case 11: mngr = theApp.GetDevManager_5_a(); lblDac = lblCurrentOutputAno2_1; break;
                case 12: mngr = theApp.GetDevManager_5_t(); lblDac = lblCurrentOutputTub2_1; break;
                    
                case 13: mngr = theApp.GetDevManager_6_a(); lblDac = lblCurrentOutputAno2_2; break;
                case 14: mngr = theApp.GetDevManager_6_t(); lblDac = lblCurrentOutputTub2_2; break;
                    
                case 15: mngr = theApp.GetDevManager_7_a(); lblDac = lblCurrentOutputAno2_3; break;
                case 16: mngr = theApp.GetDevManager_7_t(); lblDac = lblCurrentOutputTub2_3; break;
                */
            }
        
            if( mngr != null) {
                dac = mngr.GetDAC();
                nDacChannel = mngr.GetDacChannel();
                double dblLastSetDacValue = dac.GetLastSetValue( nDacChannel);
                lblDac.setText("" + String.format( "%.3f", dblLastSetDacValue) + "V");
                
                
                if( dblLastSetDacValue >= AMSConstants.DAC_MAX_OUTPUT_VOLTAGE_WARN)
                    lblDac.setForeground( Color.red);
                else if( dblLastSetDacValue <= AMSConstants.DAC_MIN_OUTPUT_VOLTAGE_WARN)
                    lblDac.setForeground( Color.red);
                else
                    lblDac.setForeground( Color.black);
                
                if( dblLastSetDacValue >= AMSConstants.DAC_MAX_OUTPUT_VOLTAGE) {
                    Font oldFont = lblDac.getFont();
                    if( !oldFont.isBold()) {
                        Font newFont = new Font( oldFont.getName(), oldFont.getStyle() + Font.BOLD, oldFont.getSize());
                        lblDac.setFont( newFont);
                    }
                }
                else if( dblLastSetDacValue <= AMSConstants.DAC_MIN_OUTPUT_VOLTAGE_WARN) {
                    Font oldFont = lblDac.getFont();
                    if( !oldFont.isBold()) {
                        Font newFont = new Font( oldFont.getName(), oldFont.getStyle() + Font.BOLD, oldFont.getSize());
                        lblDac.setFont( newFont);
                    }
                }
                else {
                    Font oldFont = lblDac.getFont();
                    if( oldFont.isBold()) {
                        Font newFont = new Font( oldFont.getName(), oldFont.getStyle() - Font.BOLD, oldFont.getSize());
                        lblDac.setFont( newFont);
                    }
                }
            }
            else
                logger.warn( "mngr = null");
        }
        
        
        
        tmrRefresh.restart();
    }
    
    public void startRefreshTimer() {
        tmrRefresh = new Timer( 1000, this);
        tmrRefresh.start();
    }
}
